packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^3.0.5
  '@ai-sdk/react': ^3.0.29
  '@hono/zod-validator': ^0.7.6
  '@opensearch-project/opensearch': ^3.5.1
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/postcss': ^4
  '@turbo/gen': ^2.7.3
  '@types/node': ^25.0.6
  '@types/react': ^19
  '@types/react-dom': ^19
  ai: ^6.0.16
  babel-plugin-react-compiler: 1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^3.6.0
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  esbuild: ^0.24.2
  eslint: ^9
  eslint-config-next: 16.1.1
  hono: ^4.11.3
  lucide-react: ^0.562.0
  next: 16.1.1
  postgres: ^3.4.8
  react: 19.2.3
  react-dom: 19.2.3
  react-icons: ^5.3.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.7.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vitest: ^4.0.16
  zod: ^4.3.5
  zod-to-json-schema: ^3.25.1
