packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^3.0.5
  '@hono/zod-validator': ^0.7.6
  '@opensearch-project/opensearch': ^3.5.1
  '@turbo/gen': ^2.7.3
  '@types/node': ^25.0.3
  ai: ^6.0.16
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  hono: ^4.11.3
  postgres: ^3.4.8
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.7.3
  typescript: ^5.9.3
  vitest: ^4.0.16
  zod: ^4.3.5
  zod-to-json-schema: ^3.25.1